version: "3"

services:

  routeros-7-5-stable:
    image: ferilagi/ros7:7.5stable
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "12222:22"
      - "12223:23"
      - "18728:8728"
      - "18729:8729"

  routeros-7-13-stable:
    image: ferilagi/ros7:7.13stable
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "22222:22"
      - "22223:23"
      - "7777:80"
      - "8728:8728"
      - "8729:8729"
      - "28728:8728"
      - "28729:8729"
